### ISSUE TITLE
survival analysis with coxph models

### ISSUE THREAD

**Issue by PedroMilanezAlmeida** [const-ae/lemur#7]
This package looks like a brilliant package, thanks again for your remarkable work!

I understand this is a really long shot... Other RNA packages don't offer this possibility, but, hey, who knows, it does not hurt (me) to ask ;)

It would definitely make the life of some users (including me, of course) a little easier if there was the possibility of fitting cox proportional hazards as well... Just saying :D

**Comment by const-ae** [comment]
> It would definitely make the life of some users (including me, of course) a little easier if there was the possibility of fitting cox proportional hazards as well... Just saying :D

Interesting suggestion. Can you say a bit more about the kind of data that you have in mind? Do you have a large matrix of features times observations of survival data?

**Comment by PedroMilanezAlmeida** [comment]
The idea would be to test for cell states associated with time to event (progression, death, recovery...). As you probably can imagine, many teams (including the one I was part of) were investigating immune cell types and states that were predictive/could explain outcome in COVID. Nowadays a lot of people are interested in using single cell data, for example, to study T cell subtypes in CAR engineering, cells in the tumor micro environment behind development of resistance to treatment, which subtypes associate with long term graft acceptance/rejection after transplantation, what states to target when boosting vaccine response, and the list goes on...

**Comment by const-ae** [comment]
Thank you for the explanation. I am still a bit confused, though. 

Abusing the R's formula notation, LEMUR relates `expr ~ covariates + latent + covariates:latent`, where  `expr` is the gene x cell gene expression matrix, `covariates` are the known factors and `latent` are the unknown factors (e.g., a continuous representation of cell type). 

Do you suggest to fit `expr ~ time_to_event + latent + time_to_event:latent`? That is, use the `time_to_event` feature as a covariate? Or do you mean `time_to_event ~ covariate + latent + covariate:latent`?

**Comment by PedroMilanezAlmeida** [comment]
Sorry, I thought you meant more in terms of potential applications.

Also, as you will realize, I have not dived into how `lemur` internally fits the linear models, and I am not a statistician nor a computer scientist. Having said that...

As you may have seen before, survival analysis with cox regression in R requires a function call with time and event as RHS, where `Surv` "transforms" the data such that the censoring information is considered as well (not only time to event itself):

```
survival::coxph(survival::Surv(time = time, event = status) ~ ph.ecog + age, data=survival::lung)
```

There is a lot of information in the (very comprehensive) vignette of the `survival` package: https://cran.r-project.org/web/packages/survival/vignettes/survival.pdf. Page 43 discusses Cox models and how to fit them with the package.

So, for `lemur`, at least in principle (and also abusing the R's formula notation), `survival::Surv(time = time, event = status) ~ covariate + latent + covariate:latent` I think would be the way to go to look at the continuous cell representation in `latent`, but I am not sure if just adding a `survival::coxph()` call around it would be feasible or do what we want it to do.

For DE testing (`expr ~ covariates + latent + covariates:latent`), I don't know if 'lemur' follows the same principle as `lm(Y~x)` to fit many columns of the matrix `Y` to the same LHS `x` in a univariate manner. As you know, working the other way around in R (`lm(y~X)`) fits a multivariate model with all columns of X. The logical step in my non-expert and narrow view would be `expr ~ survival::Surv(time = time, event = status) + covariates + latent + covariates:latent`. It's is possible (and likely wrong) to fit `lm(ph.ecog ~ survival::Surv(time = time, event = status) + age, data=survival::lung)`. However, I have no reason to believe that this call is taking the censored data into consideration correctly, rather than just fitting time as a continuous covariate and status as a dummy/numerical covariate.

If I had to guess I would say it is very complicated to add this feature, which probably is the reason why other RNA packages don't do it. The closest method and package I have heard of (but never used) is [`SAMseq`: https://rdrr.io/cran/samr/man/SAMseq.html](https://journals.sagepub.com/doi/10.1177/0962280211428386) from the `samr` package on CRAN.

So, my suggestion really is a wish, a long shot, and, again, it does not hurt (me) to ask :D Also, above, I am just trying to communicate what my limited understanding of the topic allows me convey. Probably none of it makes any sense, in which case I am sorry for wasting your time.
